export declare const Container: any;
export declare const MainLayout: any;
export declare const ContentWrapper: any;
export declare const PageTitle: any;
export declare const ChartCard: any;
export declare const CenteredTextWrapper: any;
export declare const SummaryText: any;
export declare const Highlight: any;
export declare const Suggestion: any;
